# Port
server.port=8080

# Api properties
api.base-url=https://pokeapi.co/api/v2
api.endpoint-get-pokemon=/pokemon
api.endpoint-get-type=/type
api.endpoint-get-specie=/pokemon-species
api.endpoint-get-colors=/pokemon-color
api.endpoint-get-evolution-chain=/evolution-chain
api.pokedex-min-number=1
api.pokedex-max-number=1302

# PostgresSQL properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
#jStLJw2Txefb9ZyPR5qOP3p9dZiVS02N4RtcYdWMux2A/l8xBejpo7dIyIzWCRsV
spring.datasource.hikari.data-source-properties.stringtype=unspecified

# JWT / Refresh properties
jwt.secret=${TOKEN_SECRET}
#OkC8ZUYmT2xD4jhcOnmpsB2nm7Nc7xUpXDUNZwMeAqQnYG2e1iAyRe8vZXrekFTh
jwt.user-password-min-length=8
jwt.access-mins=5
jwt.issuer=pokequiz-api
jwt.refresh-days=15

#JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Liquibase
spring.liquibase.enabled=true
# spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Server properties
server.error.whitelabel.enabled=false
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-exception=false
server.server-header=
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true

# other configurations
spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false