# Spring properties
spring.application.name=pokequiz
spring.application.version=0.0.1

# Api properties
api.baseUrl=https://pokeapi.co/api/v2

# PostgreSQL properties
spring.datasource.url=jdbc:postgresql://localhost:5432/poke_quiz
spring.datasource.username=postgres
spring.datasource.password=humano

#JPA
spring.jpa.hibernate.ddl-auto=validate

# Liquibase
spring.liquibase.enabled=true
# spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Server properties
server.error.whitelabel.enabled=false
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-exception=false
server.server-header=
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true