# Spring properties
spring.application.name=pokequiz
spring.application.version=0.0.1

# Api properties
api.baseUrl=https://pokeapi.co/api/v2

# PostgreSQL properties
spring.datasource.url=jdbc:postgresql://localhost:5432/poke_quiz
spring.datasource.username=postgres
spring.datasource.password=humano

# Server properties //FOR SECURITY

#JPA
spring.jpa.hibernate.ddl-auto=validate

# Liquibase
spring.liquibase.enabled=false